version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/node:24.5.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run lint
          command: npm run lint

  test:
    docker:
      - image: cimg/node:24.5.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run: ls -R src/components
      - run:
          name: Run Tests
          command: npm run test

  deploy_to_vercel:
    docker:
      - image: cimg/node:24.5.0
    environment:
      VERCEL_ORG_ID: $VERCEL_ORG_ID
      VERCEL_PROJECT_ID: $VERCEL_PROJECT_ID
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm ci
      - run: echo "VERCEL_PROJECT_ID=${VERCEL_PROJECT_ID}"
      - run:
          name: Pull Vercel Environment Information
          command: npx vercel pull --yes --environment=production --token=$VERCEL_TOKEN
      - run:
          name: Build Project Artifacts
          command: npx vercel build --prod --token=$VERCEL_TOKEN
      - run:
          name: Deploy Project Artifacts to Vercel
          command: npx vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN

workflows:
  version: 2
  lint_test_deploy_vercel:
    jobs:
      - lint
      - test:
          requires:
            - lint
      - deploy_to_vercel:
          requires:
            - lint
            - test
          filters:
            branches:
              only: main
